# Modify this variable to fit your NEORV32 setup (neorv32 home folder)
NEORV32_HOME ?= ../../../..
USER_FLAGS ?= -O0

include $(NEORV32_HOME)/sw/common/common.mk

copy: neorv32_exe.bin
	cp neorv32_exe.bin /mnt/c/Users/phifuc/Desktop/neorv32_binary/neorv32_exe.bin
